# 服务器基础配置
DEBUG = True
SESSION_COOKIE_NAME = "DTSession"
PERMANENT_SESSION_LIFETIME = 30 * 60
LOGGER_NAME = "DTLogger"
JSONIFY_PRETTYPRINT_REGULAR = True


# REDIS缓存
CACHE_TYPE = 'redis'
CACHE_REDIS_HOST = '127.0.0.1'
CACHE_REDIS_PORT = 6379
CACHE_REDIS_DB = '1'
CACHE_REDIS_PASSWORD = ''

# 数据库-MySQL
SQLALCHEMY_DATABASE_URI = "mysql://root:root@127.0.0.1/doc-train"
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
